spring:
  datasource:
    password: root
    username: root
    url: jdbc:mariadb://127.0.0.1:3306/transportador
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
