spring:
  datasource:
    password: 123
    username: marcio
    url: jdbc:mariadb://192.168.100.103:3306/fornecedor
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
